# Generated by Django 4.0.5 on 2024-07-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='especialidad',
            fields=[
                ('idEspecialidad', models.IntegerField(max_length=6, primary_key=True, serialize=False, verbose_name='Id Categoria')),
                ('nombre', models.CharField(max_length=50, verbose_name='Especialidad')),
            ],
        ),
    ]
