# Generated by Django 4.0.5 on 2024-07-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesfam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(db_column='genero', max_length=20)),
            ],
        ),
    ]
