# Generated by Django 4.0.5 on 2024-07-06 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cesfam', '0002_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='medico',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('appaterno', models.CharField(max_length=30, verbose_name='Apellido Paterno')),
                ('apmaterno', models.CharField(max_length=30, verbose_name='Apellido Materno')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cesfam.especialidad')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cesfam.genero')),
            ],
        ),
    ]
