# Generated by Django 4.0.5 on 2024-07-06 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cesfam', '0003_medico'),
    ]

    operations = [
        migrations.CreateModel(
            name='ficha',
            fields=[
                ('nFicha', models.IntegerField(db_column='nFicha', primary_key=True, serialize=False, verbose_name='Numero de Ficha')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('rut', models.CharField(max_length=10, verbose_name='Rut')),
            ],
        ),
        migrations.CreateModel(
            name='sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='sector', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='idEspecialidad',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Categoria'),
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('appaterno', models.CharField(max_length=30, verbose_name='Apellido Paterno')),
                ('apmaterno', models.CharField(max_length=30, verbose_name='Apellido Materno')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('genero', models.ForeignKey(db_column='genero', on_delete=django.db.models.deletion.CASCADE, to='cesfam.genero')),
                ('nFicha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cesfam.ficha')),
            ],
        ),
        migrations.AddField(
            model_name='ficha',
            name='sector',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='cesfam.sector'),
        ),
    ]
