# Generated by Django 4.0.5 on 2024-07-06 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cesfam', '0004_ficha_sector_alter_especialidad_idespecialidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='atencion',
            fields=[
                ('idAtencion', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('historial', models.TextField(max_length=1500)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cesfam.especialidad')),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cesfam.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('fecha', models.DateField()),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cesfam.especialidad')),
            ],
        ),
    ]
