# Generated by Django 4.0.5 on 2024-07-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesfam', '0005_atencion_agenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('stock', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
            ],
        ),
    ]
