# Generated by Django 4.0.5 on 2024-07-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesfam', '0007_medico_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='genero',
            field=models.BooleanField(db_column='genero', max_length=20),
        ),
    ]
