# Generated by Django 4.0.5 on 2024-07-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesfam', '0008_alter_genero_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='genero',
            field=models.CharField(db_column='genero', max_length=20),
        ),
    ]
